routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PegawaiController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});


Route::resource('pegawais', PegawaiController::class);

app/Models/Pegawai.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pegawai extends Model
{
    use HasFactory;
    protected $fillable = ['nama', 'posisi', 'umur'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PegawaiController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Models\Pegawai;

class PegawaiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pegawai = Pegawai::all();
        return view('index', compact('pegawai'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return View('create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $storeData = $request->validate([
            'nama' => 'required|max:255',
            'posisi' => 'required|max:255',
            'umur' => 'required|numeric',
        ]);
        $pegawai = Pegawai::create($storeData);
        return redirect('/pegawais')->with('Sukses', 'Pegawai berhasil di tambahkan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $pegawai = Pegawai::findOrFail($id);
        return view('edit', compact('pegawai'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $updateData = $request->validate([
            'nama' => 'required|max:255',
            'posisi' => 'required|max:255',
            'umur' => 'required|numeric',
        ]);

        Pegawai::whereId($id)->update($updateData);
        return redirect('/pegawais')->with('Sukses', 'Pegawai berhasil di tambahkan!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $pegawai = Pegawai::findOrFail($id);
        $pegawai->delete();

        return redirect('/pegawais')->with('Sukses', 'Data berhasil di hapus');
    }
}

resources/views/create.blade.php
@extends('layout')

@section('content')

<style>
    .container {
      max-width: 450px;
    }
    .push-top {
      margin-top: 50px;
    }
</style>

<div class="card push-top text-white bg-dark">
  <div class="card-header">
    <h3 style="text-align: center">Tambah Data</h3>
  </div>

  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('pegawais.store') }}">
          <div class="form-group">
              @csrf
              <label for="nama">Nama</label>
              <input type="text" class="form-control" name="nama"/>
          </div>
          <div class="form-group">
              <label for="posisi">Posisi</label>
              <input type="text" class="form-control" name="posisi"/>
          </div>
          <div class="form-group">
              <label for="umur">Umur</label>
              <input type="text" class="form-control" name="umur"/>
          </div>
          <button type="submit" class="btn btn-block btn-secondary">Tambahkan</button>
      </form>
  </div>
</div>
@endsection

resources/views/edit.blade.php
@extends('layout')

@section('content')

<style>
    .container {
      max-width: 450px;
    }
    .push-top {
      margin-top: 50px;
    }
</style>

<div class="card push-top text-white bg-dark">
  <div class="card-header">
    Edit Data
  </div>

  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('pegawais.update', $pegawai->id) }}">
          <div class="form-group">
              @csrf
              @method('PATCH')
              <label for="nama">Nama</label>
              <input type="text" class="form-control" name="nama" value="{{ $pegawai->nama }}"/>
          </div>
          <div class="form-group">
              <label for="posisi">Posisi</label>
              <input type="posisi" class="form-control" name="posisi" value="{{ $pegawai->posisi }}"/>
          </div>
          <div class="form-group">
              <label for="umur">Umur</label>
              <input type="text" class="form-control" name="umur" value="{{ $pegawai->umur }}"/>
          </div>
          <button type="submit" class="btn btn-block btn-secondary">SIMPAN</button>
      </form>
  </div>
</div>
@endsection

resources/views/home.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>UTS Web Programming</title>
    <style>
        .header {
            text-align: center;
            font-family: Arial;
            font-weight: bold;
        }
    </style>
</head>
<body>

    <h1 class="header"">CRUD Using Laravel 8 and MySQL</h1>

    <p style="text-align: center"><a href="http://uts-webpro.test/pegawais">Click here to go to the main page</a></p>
    
</body>
</html>

resources/views/index.blade.php
@extends('layout')

@section('content')

<style>
  .push-top {
    margin-top: 20px;
    margin-bottom: 20px;
  }
  body {
    background-color : black;
  }
</style>

  <div class="push-top">
    <a href="{{ route('pegawais.create')}}" class="btn btn-info btn-sm">Tambah</a>
  </div>
  <table class="table">
    <thead>
        <tr class="table-info text-uppercase fs-1">
          <th>Nama</th>
          <th>Posisi</th>
          <th>Umur</th>
          <th class="text-center">Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach($pegawai as $pegawais)
        <tr class="table-light">
            <th>{{$pegawais->nama}}</th>
            <td>{{$pegawais->posisi}}</td>
            <td>{{$pegawais->umur}}</td>
            <td class="text-center">
                <a href="{{ route('pegawais.edit', $pegawais->id)}}" class="btn btn-outline-warning btn-sm"">Edit</a>
                <form action="{{ route('pegawais.destroy', $pegawais->id)}}" method="post" style="display: inline-block">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-outline-danger btn-sm"" type="submit">Hapus</button>
                  </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <title>UTS Web Programming | Data Pegawai</title>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
   </head>
   <body>

      <div class="container">
         @yield('content')
      </div>

      <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" type="text/js"></script>
   </body>
</html>